name: Deploy Flask App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/cicd-demo
            git pull origin main
            pip3 install --user -r requirements.txt
            sudo systemctl restart cicd-demo
            sudo systemctl is-active --quiet cicd-demo
            curl -f http://localhost:5000/health